### ISSUE TITLE
ERR_CONNECTION_REFUSED after fresh install

### ISSUE THREAD

**Issue by avp90** [zoneminder-containers/zoneminder-base#30]
What are you using in your docker compose file? It seems that zoneminder is having issues starting up.

_Originally posted by @alexyao2015 in https://github.com/zoneminder-containers/zoneminder-base/issues/29#issuecomment-1067273573_

That's the `docker-compose.yml` file content:
```
version: '3.6'

services:
  # !! WARNING: !!
  # If using linuxserver/mariadb, you will need to add
  # skip-log-bin to mysqld and disable all log_bin options
  db:
    image: mariadb:10.7.3
    restart: always
    container_name: zm_db
    ports:
      - 3306:3306
    volumes:
      - ./zm/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=zm
    env_file:
      - ./.env

  zoneminder:
    image: ghcr.io/zoneminder-containers/zoneminder-base:1.36.12
    restart: always
    container_name: zm
    stop_grace_period: 45s
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./zm/data:/data
      - ./zm/config:/config
      - ./zm/log:/log
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 1000000000
    env_file:
      - ./.env
```
